[package]
name = "generateLayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
rand = "0.8.5"

[dev-dependencies]
assert_cmd = "2"
tempfile = "3.8.0"